create table if not exists public.minecrafthud_downloads (
  id bigint generated by default as identity primary key,
  source text not null default 'website',
  created_at timestamptz not null default now()
);

alter table public.minecrafthud_downloads enable row level security;
